### ISSUE TITLE
[BUG] Pause doesn't work

### ISSUE THREAD

**Issue by blahdy** [Michael-128/qBitControl#9] opened 2024-04-21 13:20 UTC
**Describe the bug**
Pause doesn't work, nor can a paused torrent be resumed.

**Smartphone (please complete the following information):**
 - Device: [ios 17]
qbittorrent is from the master branch

**Comment by Michael-128** [comment] 2024-04-23 08:01
I can't reproduce the bug. Could you give me more details?

**Comment by Michael-128** [comment] 2024-06-02 18:53
I will close the issue as there is no further activity.

**Closed by Michael-128** 2024-06-02 18:53 UTC
Labels: bug
